# Generated by Django 3.1.4 on 2021-01-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist_currant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='currant_price',
        ),
    ]
