# Generated by Django 3.1.4 on 2021-01-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_watchlist_currant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buying', to='auctions.auctionlisting'),
        ),
    ]
